"use client";
import {useEffect,useState} from "react";
import {Input} from "@/components/ui/input";
import Connection from "../connection";
import Catalog from "../catalog";
import Promotions from "../promotions";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
const products: [string,number][]=[["Short de linho",17],["Kit com 2 shorts de linho",34],["Demais shorts",20],["Vestido canelado",20],["Sutiã Plus Size",33],["Blusa 3 zíper",42],["Moletom de gola",50],["Conjunto",68],["Kit com 2 moletons",84],["Kit com 3 moletons",126],["Kit com 4 moletons",168],["Kit com 1 blusa e 2 calças",94],["Kit com 1 moletom e 1 camiseta",54],["Coturno Adventure",150]];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Home(){
 const [price,P]=useState("159.90"),[cost,C]=useState("42"),[fee,F]=useState("22.386"),[shipping,S]=useState("26");
 const values=[price,cost,fee,shipping]; const valid=values.every(v=>v.trim()!==""&&Number.isFinite(Number(v))&&Number(v)>=0)&&Number(price)>0;
 const [v,c,t,f]=values.map(Number);const commission=(v-t-f)*.03;const profit=v-t-f-v*.09-v*.05-14-c-commission;const margin=profit/v*100;const accepted=valid&&v-t-f>=0&&profit>=v*.04;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:"read_pilot_simulation",description:"Lê a simulação atual, sem aderir a promoções ou alterar anúncios.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw Error("Entrada deve ser um objeto vazio");return {valid,profit:valid?profit:null,margin:valid?margin:null,accepted,connected:false};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[valid,profit,margin,accepted]);
 return <main><header><div className="brand">GP<span>Gestor de Promoções</span></div><span className="badge">Dherik · Piloto 01</span></header><div className="workspace"><div className="title"><div><p className="eyebrow">MERCADO LIVRE</p><h1>Controle da margem.</h1><p>Configure sua conta e confira a margem de cada venda.</p></div><span className="status">Adesão automática desativada</span></div>
 <Connection/>
 <Catalog/>
 <Promotions/>
 <section className="metrics" aria-label="Regras da conta">{[["Imposto","9%","Sobre a venda"],["Comissão interna","3%","Após taxas e frete"],["Publicidade","5%","Reserva sobre a venda"],["Margem mínima","4%","Após todos os custos"]].map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</section>
 <div className="columns"><section className="panel"><h2>Simular uma venda</h2><p>Valores manuais para conferir a regra. Sem subsídio nesta simulação.</p><div className="inputs">{[["Preço de venda (R$)",price,P],["Custo do SKU (R$)",cost,C],["Taxas da plataforma (R$)",fee,F],["Frete por sua conta (R$)",shipping,S]].map(([label,value,set],i)=><label key={i}>{label as string}<Input type="number" min="0" step="any" value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}</div><div className="breakdown"><p>Despesa fixa por SKU <b>R$ 14,00</b></p><p>Imposto <b>{valid?money(v*.09):"—"}</b></p><p>Publicidade <b>{valid?money(v*.05):"—"}</b></p><p>Comissão interna <b>{valid&&v-t-f>=0?money(commission):"—"}</b></p></div><div className={"result "+(accepted?"pass":"fail")} aria-live="polite"><span>{!valid||v-t-f<0?"Revise os valores":accepted?"Atende à margem mínima":"Abaixo da margem mínima"}</span><strong>{valid&&v-t-f>=0?money(profit):"—"}</strong><p>{valid&&v-t-f>=0?margin.toFixed(2).replace(".",",")+"% de margem estimada":"Preencha valores válidos para calcular."}</p></div><p className="small">A decisão usa o valor sem arredondamento. Taxas e frete devem corresponder ao preço simulado. Esta tela não inscreve anúncios em promoções.</p></section>
 <section className="panel"><h2>Custos por produto e kit</h2><p>Uma despesa fixa de R$ 14,00 por SKU, inclusive nos kits. O custo dos kits já representa o conteúdo total do SKU.</p><Table><TableHeader><TableRow><TableHead>Produto / kit</TableHead><TableHead className="number">Custo</TableHead></TableRow></TableHeader><TableBody>{products.map(([name,cost])=><TableRow key={name}><TableCell>{name}</TableCell><TableCell className="number">{money(cost)}</TableCell></TableRow>)}</TableBody></Table><div className="note"><b>Identificação dos SKUs</b><p>O sistema verifica primeiro kits e conjuntos. Reconhece kits com 2 shorts de linho, SHORT-LIN/SHORT-LINH, SUT de anúncios Plus Size, MOL-3ZIP, 3ZIP, MOL-GOLA, CONJ-3ZIP e kits 3 zíper. Cor e tamanho não alteram o custo. Códigos ambíguos continuam pendentes de revisão.</p></div></section></div><footer>Modo de preparação · Adesão automática desativada</footer></div></main>
}
