"use client";
import {useEffect,useState} from "react";
import {Input} from "@/components/ui/input";import {Button} from "@/components/ui/button";
type Status={configured?:boolean;connected?:boolean;nickname?:string;error?:string};
export default function Connection(){const [s,S]=useState<Status>({}),[secret,K]=useState(""),[busy,B]=useState(false),[editing,E]=useState(false),[message,M]=useState("");
async function refresh(){try{const r=await fetch("/api/mercado-livre/status",{cache:"no-store"});const d=await r.json() as Status;S(d);if(d.error)M(d.error)}catch{M("Não foi possível consultar a conexão. Recarregue a página.")}}
useEffect(()=>{void refresh();const q=new URLSearchParams(location.search).get("conexao");const messages:Record<string,string>={sucesso:"Conta autorizada. Nenhum anúncio foi alterado.",falhou:"A autorização não foi concluída. Confira a chave, o endereço de retorno e as permissões, e tente novamente.",invalida:"A autorização expirou ou foi aberta em outra sessão. Inicie novamente por este painel.",cancelada:"Autorização cancelada. Você pode tentar novamente.",configuracao:"A configuração mudou. Inicie a autorização novamente."};if(q){M(messages[q]??"Verifique a conexão.");history.replaceState(null,"",location.pathname)}},[]);
async function save(e:React.FormEvent){e.preventDefault();B(true);M("");try{const r=await fetch("/api/mercado-livre/configuracao",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({secret})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??"Falha ao salvar");K("");E(false);M("Chave cadastrada. Agora autorize sua conta no Mercado Livre.");await refresh()}catch(e){M(e instanceof Error?e.message:"Falha ao salvar. Tente novamente.")}finally{B(false)}}
return <section className="connection"><div style={{width:"100%"}}><h2>{s.connected?"Conta autorizada: "+s.nickname:"Conectar sua conta"}</h2><p>{s.connected?"A autorização foi recebida. Use a seção Anúncios e SKUs para importar seus produtos. Adesão automática desativada.":"Cadastre a chave secreta deste aplicativo aqui e depois autorize o acesso no Mercado Livre."}</p><p className="small">Aplicativo: 5716651302555823 · Gestor de Promoções Teste 01</p>{(!s.configured||editing)&&!s.error&&<form onSubmit={save} style={{maxWidth:520}}><label htmlFor="ml-secret">Chave secreta do aplicativo</label><Input id="ml-secret" type="password" autoComplete="off" spellCheck={false} required minLength={16} maxLength={512} value={secret} onChange={e=>K(e.target.value)}/><p className="small">Ao salvar, a conexão anterior será removida. Enviada por HTTPS e armazenada criptografada no servidor. Não é exibida novamente nem enviada ao chat.</p><Button type="submit" disabled={busy||!secret}>{busy?"Salvando…":"Salvar chave secreta"}</Button></form>}{s.configured&&!editing&&<form method="POST" action="/api/mercado-livre/autorizar" target="_top"><Button type="submit">{s.connected?"Autorizar novamente":"Autorizar no Mercado Livre"}</Button></form>}{s.configured&&<Button variant="outline" onClick={()=>E(!editing)} style={{marginTop:12}}>{editing?"Cancelar troca":"Trocar chave secreta"}</Button>}<p role="status">{message}</p><details><summary>Conferir endereço de retorno</summary><code>https://gestor-promocoes-dherik.dherikjcamargo.chatgpt.site/integracoes/mercado-livre/retorno</code></details><p className="small">Se estiver vendo o painel dentro do ChatGPT, <a href="https://gestor-promocoes-dherik.dherikjcamargo.chatgpt.site" target="_blank" rel="noopener noreferrer" style={{textDecoration:"underline"}}>abra em uma nova aba</a> antes de autorizar.</p></div></section>}
