import {integer,primaryKey,sqliteTable,text} from "drizzle-orm/sqlite-core";
export const mlAccounts=sqliteTable("ml_accounts",{owner:text("owner").primaryKey(),secret:text("secret").notNull(),tokens:text("tokens"),sellerId:text("seller_id"),nickname:text("nickname"),expiresAt:integer("expires_at"),updatedAt:integer("updated_at").notNull()});
export const mlOauthStates=sqliteTable("ml_oauth_states",{stateHash:text("state_hash").primaryKey(),owner:text("owner").notNull(),verifier:text("verifier").notNull(),browserHash:text("browser_hash").notNull(),expiresAt:integer("expires_at").notNull()});
export const mlImports=sqliteTable("ml_imports",{owner:text("owner").primaryKey(),sellerId:text("seller_id").notNull(),run:text("run").notNull(),payload:text("payload").notNull(),cursor:text("cursor"),processed:integer("processed").notNull(),total:integer("total").notNull(),done:integer("done").notNull(),lease:text("lease"),lockedUntil:integer("locked_until").notNull(),updatedAt:integer("updated_at").notNull()});
// Custos editados na lista de anúncios; ausência de linha = custo padrão de lib/product-costs.ts.
export const productCosts=sqliteTable("product_costs",{owner:text("owner").notNull(),product:text("product").notNull(),costCents:integer("cost_cents").notNull(),updatedAt:integer("updated_at").notNull()},t=>[primaryKey({columns:[t.owner,t.product]})]);
// Regras de margem editadas na lista (JSON de MarginRules); ausência de linha = padrões de lib/offer-analysis.ts.
export const marginRules=sqliteTable("margin_rules",{owner:text("owner").primaryKey(),rules:text("rules").notNull(),updatedAt:integer("updated_at").notNull()});
// Registro de cada tentativa de adesão (antes do envio e resultado), para auditoria.
export const participationLog=sqliteTable("participation_log",{id:integer("id").primaryKey({autoIncrement:true}),owner:text("owner").notNull(),itemId:text("item_id").notNull(),promotionId:text("promotion_id"),promotionType:text("promotion_type"),refId:text("ref_id").notNull(),expectedPriceCents:integer("expected_price_cents"),resultPriceCents:integer("result_price_cents"),status:text("status").notNull(),detail:text("detail").notNull(),createdAt:integer("created_at").notNull()});
