import {actor,account,runtime,REDIRECT,COOKIE,back} from "@/lib/mercado-livre";
import {hash,seal,unseal} from "@/lib/ml-crypto";
export async function GET(request:Request){
try{const owner=await actor();const e=runtime();const url=new URL(request.url);const state=url.searchParams.get("state"),code=url.searchParams.get("code");const browser=(request.headers.get("cookie")??"").split(";").map(s=>s.trim()).find(s=>s.startsWith(COOKIE+"="))?.slice(COOKIE.length+1);
if(!state||state.length>512||!browser||browser.length>512)return back("invalida");
const row=await e.DB.prepare("DELETE FROM ml_oauth_states WHERE state_hash=? AND owner=? AND browser_hash=? AND expires_at>? RETURNING verifier").bind(await hash(state),owner,await hash(browser),Date.now()).first<{verifier:string}>();if(!row)return back("invalida");if(url.searchParams.has("error"))return back("cancelada");if(!code||code.length>2048)return back("invalida");const a=await account(owner);if(!a)return back("configuracao");
const verifier=await unseal(row.verifier,e.ML_ENCRYPTION_KEY,owner+":pkce");const secret=await unseal(a.secret,e.ML_ENCRYPTION_KEY,owner+":secret");
const res=await fetch("https://api.mercadolibre.com/oauth/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded","Accept":"application/json"},body:new URLSearchParams({grant_type:"authorization_code",client_id:e.ML_CLIENT_ID,client_secret:secret,code,redirect_uri:REDIRECT,code_verifier:verifier}),signal:AbortSignal.timeout(20000)});if(!res.ok)return back("falhou");const t=await res.json() as {access_token?:string;refresh_token?:string;expires_in?:number;user_id?:number};if(!t.access_token||!t.refresh_token||!t.user_id||!Number.isFinite(t.expires_in)||Number(t.expires_in)<=0)return back("falhou");
const me=await fetch("https://api.mercadolibre.com/users/me",{headers:{Authorization:"Bearer "+t.access_token},signal:AbortSignal.timeout(15000)});if(!me.ok)return back("falhou");const profile=await me.json() as {id:number;nickname?:string};if(String(profile.id)!==String(t.user_id))return back("falhou");
const tokens=await seal(JSON.stringify({access_token:t.access_token,refresh_token:t.refresh_token}),e.ML_ENCRYPTION_KEY,owner+":tokens");const result=await e.DB.prepare("UPDATE ml_accounts SET tokens=?,seller_id=?,nickname=?,expires_at=?,updated_at=? WHERE owner=? AND secret=?").bind(tokens,String(t.user_id),profile.nickname??String(t.user_id),Date.now()+Number(t.expires_in)*1000,Date.now(),owner,a.secret).run();if(!result.meta.changes)return back("configuracao");return back("sucesso");
}catch{return back("falhou")}}
